//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fallout3Fixer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fallout3Fixer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] gfwlclient {
            get {
                object obj = ResourceManager.GetObject("gfwlclient", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\Software\Classes\Software\Microsoft\XLive]
        ///&quot;PCID&quot;=hex(b):00,bb,af,e2,6b,10,f5,c3
        ///&quot;Version&quot;=dword:32000300
        ///&quot;SqmOptin&quot;=dword:00000001
        ///&quot;ConnectionOverride&quot;=&quot;&quot;
        ///&quot;Default_Profile&quot;=hex:af,e2,6b,10,fb,00,00,e0
        ///&quot;DLCBasePath&quot;=&quot;D:\Games\WindowsApps&quot;
        ///&quot;XUIDCount&quot;=dword:00000001
        ///&quot;GuideKey&quot;=hex(b):24,00,00,00,00,00,00,00
        ///
        ///[HKEY_CURRENT_USER\Software\Classes\Software\Microsoft\XLive\E00000FB106BE2AF]
        ///&quot;PlayDevice&quot;=hex:1a,d7,6d,bd,eb,3d,d1,11,b1,71,00,c0,4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string registrymod {
            get {
                return ResourceManager.GetString("registrymod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] winlivedisable {
            get {
                object obj = ResourceManager.GetObject("winlivedisable", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xliveredist {
            get {
                object obj = ResourceManager.GetObject("xliveredist", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
